apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceable-backend
  # metadata.name是 这个 Deployment 资源在 Kubernetes 里的名字。
  # kubectl get deployments可以看到它。
spec:
# spec 是 希望这个资源"长成什么样"。
  replicas: 3
  # 这个数字1代表着，希望永远有 1 个这样的 Pod 在运行。
  selector:
    matchLabels:
      app: traceable-backend
      # 在 Kubernetes 里，每个资源（Pod、Service、Deployment…）都可以带标签。标签本质是，key: value。
      # 上面这几行的意思是， Deployment 负责管理所有带有 app=traceable-backend 标签的 Pod，其中app和traceable-backend都没有具体含义，只代表标签。
      # 顺便讲一下 Pod 的名字，Deployment 创建 Pod 时，会自动生成名字，格式是：<deployment-name>-<replicaset-hash>-<随机后缀>。
  template:
  # template 相当于 "Pod 的制造蓝图"。
    metadata:
      labels:
        app: traceable-backend
    spec:
    # 这里的 spec 是 希望 pod"长成什么样"。
      topologySpreadConstraints:
        - maxSkew: 1
          # maxSkew 是允许各节点之间 Pod 数量的最大差值。
          # 设为 1 表示：任意两个节点上的 Pod 数量差不能超过 1。
          topologyKey: kubernetes.io/hostname
          # topologyKey 决定以什么维度来"分散"。
          # kubernetes.io/hostname 表示以节点（机器）为单位来分散 Pod。
          whenUnsatisfiable: ScheduleAnyway
          # 当无法满足分散约束时的兜底策略。
          # ScheduleAnyway 表示：即使无法满足约束，也照常调度，不卡住。
          # 另一个选项是 DoNotSchedule，会直接让 Pod 处于 Pending 状态。
          labelSelector:
            matchLabels:
              app: traceable-backend
              # 告诉 Kubernetes 统计哪些 Pod 的分布。
              # 这里匹配所有带 app=traceable-backend 标签的 Pod，和 selector 保持一致。
      containers:
        - name: backend
          # 一个 Pod 里有多个容器时，用名字区分。
          image: traceable-backend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              # 声明容器内部监听的端口。
          envFrom:
            # envFrom 会把整个 ConfigMap / Secret 里的所有 key 都注入为环境变量
            # 比逐条写 env: - name: ... value: ... 简洁很多
            - configMapRef:
                name: backend-config   # 对应 configmap.yaml
            - secretRef:
                name: backend-secret   # 对应 secret.yaml（敏感变量）

          volumeMounts:
            - name: artifact-storage
              mountPath: /app/data/artifacts
            - name: audit-storage
              mountPath: /app/data/audit

      volumes:
        - name: artifact-storage
          persistentVolumeClaim:
            claimName: artifact-pvc   # 对应 pvc.yaml
        - name: audit-storage
          persistentVolumeClaim:
            claimName: audit-pvc      # 对应 pvc.yaml
