apiVersion: v1
kind: Service
metadata:
  name: traceable-backend
spec:
  type: NodePort
  selector:
    app: traceable-backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
      # Node 把 30080 转发给 Service，Service 再把 80 转发给 Pod 的 8000
