"""add daily token usage

Revision ID: 5d2d67a9de8c
Revises: 6752eb8bc020
Create Date: 2026-02-19 14:39:17.289057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d2d67a9de8c'
down_revision = '6752eb8bc020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_token_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_daily_token_usage_user_date')
    )
    op.create_index('ix_user_daily_token_usage_date_user', 'user_daily_token_usage', ['usage_date', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_daily_token_usage_id'), 'user_daily_token_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_token_usage_usage_date'), 'user_daily_token_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_user_daily_token_usage_user_id'), 'user_daily_token_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_token_usage_user_id'), table_name='user_daily_token_usage')
    op.drop_index(op.f('ix_user_daily_token_usage_usage_date'), table_name='user_daily_token_usage')
    op.drop_index(op.f('ix_user_daily_token_usage_id'), table_name='user_daily_token_usage')
    op.drop_index('ix_user_daily_token_usage_date_user', table_name='user_daily_token_usage')
    op.drop_table('user_daily_token_usage')
    # ### end Alembic commands ###
